import os

file_path = r's:\2K27_Project\shoplens\frontend\src\pages\seller\SellerQuickCatalog.jsx'

replacements = {
    # Automobile
    "id: 'engine_oils_lubes',": "id: 'engine_oils_lubes', unitType: 'weight_vol', allowedUnits: ['L', 'ml', 'kg', 'tin'],",
    "id: 'two_wheeler_body',": "id: 'two_wheeler_body', unitType: 'count', allowedUnits: ['pc', 'set', 'pair'],",
    "id: 'cables_mechanicals',": "id: 'cables_mechanicals', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'electrical_parts_auto',": "id: 'electrical_parts_auto', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'filters_gaskets',": "id: 'filters_gaskets', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",
    "id: 'tyres_tubes_auto',": "id: 'tyres_tubes_auto', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'car_accessories_general',": "id: 'car_accessories_general', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'safety_gear_auto',": "id: 'safety_gear_auto', unitType: 'count', allowedUnits: ['pc'],",

    # Industrial
    "id: 'power_tools_corded',": "id: 'power_tools_corded', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'cordless_tools',": "id: 'cordless_tools', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'abrasives_wheels',": "id: 'abrasives_wheels', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'drill_bits_chisels',": "id: 'drill_bits_chisels', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'welding_equipment',": "id: 'welding_equipment', unitType: 'count', allowedUnits: ['pc', 'set', 'kg', 'pkt'],",
    "id: 'industrial_hand_tools',": "id: 'industrial_hand_tools', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'measuring_instruments',": "id: 'measuring_instruments', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'safety_gear_industrial',": "id: 'safety_gear_industrial', unitType: 'count', allowedUnits: ['pc', 'pair'],",
    "id: 'pneumatics_air_tools',": "id: 'pneumatics_air_tools', unitType: 'count', allowedUnits: ['pc', 'set', 'length'],",

    # Tools Others
    "id: 'ladders_climbing',": "id: 'ladders_climbing', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'torches_emergency',": "id: 'torches_emergency', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'weighing_scales',": "id: 'weighing_scales', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'pest_control_elec',": "id: 'pest_control_elec', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'ropes_tying',": "id: 'ropes_tying', unitType: 'length', allowedUnits: ['m', 'ft', 'bundle', 'kg'],",
    "id: 'home_utility_gen',": "id: 'home_utility_gen', unitType: 'count', allowedUnits: ['pc', 'set', 'length'],",
    "id: 'batteries_general',": "id: 'batteries_general', unitType: 'count', allowedUnits: ['pc', 'pkt', 'box'],",

    # Mobile & Computer
    "id: 'mobile_handsets',": "id: 'mobile_handsets', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'phone_covers',": "id: 'phone_covers', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'screen_guards',": "id: 'screen_guards', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'chargers_cables',": "id: 'chargers_cables', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'audio_accessories',": "id: 'audio_accessories', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'holders_stands',": "id: 'holders_stands', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'power_banks_storage',": "id: 'power_banks_storage', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'smart_wearables',": "id: 'smart_wearables', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'comp_laptops',": "id: 'comp_laptops', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'input_devices',": "id: 'input_devices', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'monitors_display',": "id: 'monitors_display', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'storage_devices_comp',": "id: 'storage_devices_comp', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'printers_scanners',": "id: 'printers_scanners', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'networking_internet',": "id: 'networking_internet', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'audio_multimedia_pc',": "id: 'audio_multimedia_pc', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'cables_adapters_comp',": "id: 'cables_adapters_comp', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'comp_components',": "id: 'comp_components', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'printer_consumables',": "id: 'printer_consumables', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'software_antivirus',": "id: 'software_antivirus', unitType: 'count', allowedUnits: ['pc', 'user'],",
    "id: 'comp_acc_care',": "id: 'comp_acc_care', unitType: 'count', allowedUnits: ['pc'],",

    # Consumer Electronics
    "id: 'home_televisions',": "id: 'home_televisions', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'refrigerators_freeze',": "id: 'refrigerators_freeze', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'washing_machines',": "id: 'washing_machines', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'ac_coolers',": "id: 'ac_coolers', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'kitchen_appliances_elec',": "id: 'kitchen_appliances_elec', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'water_solutions',": "id: 'water_solutions', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'home_care_cleaning',": "id: 'home_care_cleaning', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'home_ent_audio',": "id: 'home_ent_audio', unitType: 'count', allowedUnits: ['pc'],",

    # Repair
    "id: 'mobile_parts_internal',": "id: 'mobile_parts_internal', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'soldering_equipment',": "id: 'soldering_equipment', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'repair_tools_kits',": "id: 'repair_tools_kits', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'battery_power_comp',": "id: 'battery_power_comp', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'loose_electronics',": "id: 'loose_electronics', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'cables_connectors_diy',": "id: 'cables_connectors_diy', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'test_measure_inst',": "id: 'test_measure_inst', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'repair_cleaning_chem',": "id: 'repair_cleaning_chem', unitType: 'weight_vol', allowedUnits: ['pc', 'bottle', 'spray', 'ml'],",
    "id: 'specialized_tapes_insul',": "id: 'specialized_tapes_insul', unitType: 'count', allowedUnits: ['pc', 'roll'],",
    "id: 'workshop_organizers',": "id: 'workshop_organizers', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'optical_aids_repair',": "id: 'optical_aids_repair', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'misc_consumables_tech',": "id: 'misc_consumables_tech', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",

    # Stationery & Books
    "id: 'notebooks_paper',": "id: 'notebooks_paper', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'writing_pens_pencils',": "id: 'writing_pens_pencils', unitType: 'count', allowedUnits: ['pc', 'pkt', 'box'],",
    "id: 'geometry_math_tools',": "id: 'geometry_math_tools', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'exam_essentials',": "id: 'exam_essentials', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'coloring_art_basic',": "id: 'coloring_art_basic', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'adhesives_craft_school',": "id: 'adhesives_craft_school', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'school_textbooks',": "id: 'school_textbooks', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'guides_reference',": "id: 'guides_reference', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'college_university',": "id: 'college_university', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'competitive_exams',": "id: 'competitive_exams', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'fiction_literature',": "id: 'fiction_literature', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'childrens_books',": "id: 'childrens_books', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'dictionaries_maps',": "id: 'dictionaries_maps', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'religious_spiritual_books',": "id: 'religious_spiritual_books', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'forms_stationery_books',": "id: 'forms_stationery_books', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'paints_mediums_prof',": "id: 'paints_mediums_prof', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'canvases_surfaces',": "id: 'canvases_surfaces', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'brushes_tools_art',": "id: 'brushes_tools_art', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'sketching_illustration',": "id: 'sketching_illustration', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'craft_diy_materials',": "id: 'craft_diy_materials', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'papers_decoration_craft',": "id: 'papers_decoration_craft', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'modeling_sculpting',": "id: 'modeling_sculpting', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt', 'kg'],",
    "id: 'embellishments_craft',": "id: 'embellishments_craft', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",
    "id: 'copier_printing_paper',": "id: 'copier_printing_paper', unitType: 'count', allowedUnits: ['pkt', 'ream', 'box'],",
    "id: 'files_folders_org',": "id: 'files_folders_org', unitType: 'count', allowedUnits: ['pc', 'pkt', 'box'],",
    "id: 'desktop_stationery_tools',": "id: 'desktop_stationery_tools', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'stamps_ink_office',": "id: 'stamps_ink_office', unitType: 'count', allowedUnits: ['pc', 'bottle'],",
    "id: 'calculators_elec_office',": "id: 'calculators_elec_office', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'binding_lamination',": "id: 'binding_lamination', unitType: 'count', allowedUnits: ['pc', 'pkt', 'roll'],",
    "id: 'writing_marking_office',": "id: 'writing_marking_office', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'id_cards_accessories',": "id: 'id_cards_accessories', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",
    "id: 'boards_display_equip',": "id: 'boards_display_equip', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'gifting_packaging',": "id: 'gifting_packaging', unitType: 'count', allowedUnits: ['pc', 'pkt', 'roll'],",
    "id: 'party_celebration',": "id: 'party_celebration', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'sports_games_stat',": "id: 'sports_games_stat', unitType: 'count', allowedUnits: ['pc', 'set', 'pair'],",
    "id: 'seasonal_gujarat',": "id: 'seasonal_gujarat', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",
    "id: 'organizers_utility_stat',": "id: 'organizers_utility_stat', unitType: 'count', allowedUnits: ['pc'],",

    # Kitchen & Cleaning
    "id: 'pressure_cookers',": "id: 'pressure_cookers', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'cooking_utensils_topes',": "id: 'cooking_utensils_topes', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'tawa_non_stick',": "id: 'tawa_non_stick', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'ss_dining_thali',": "id: 'ss_dining_thali', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'storage_dabba',": "id: 'storage_dabba', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'kitchen_tools_gadgets',": "id: 'kitchen_tools_gadgets', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'cutlery_knives',": "id: 'cutlery_knives', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'bottles_flasks',": "id: 'bottles_flasks', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'plasticware_kitchen',": "id: 'plasticware_kitchen', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'cleaning_tools_home',": "id: 'cleaning_tools_home', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'bathroom_utility_plastics',": "id: 'bathroom_utility_plastics', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'brooms_mops_cleaning',": "id: 'brooms_mops_cleaning', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'brushes_scrubbers',": "id: 'brushes_scrubbers', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'dustbins_waste_mgmt',": "id: 'dustbins_waste_mgmt', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'laundry_organization',": "id: 'laundry_organization', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'kitchen_plastics_storage',": "id: 'kitchen_plastics_storage', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'mats_flooring_home',": "id: 'mats_flooring_home', unitType: 'count', allowedUnits: ['pc'],",

    # Gifts & Toys
    "id: 'soft_toys_plush',": "id: 'soft_toys_plush', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'elec_rc_toys',": "id: 'elec_rc_toys', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'dolls_action_figures',": "id: 'dolls_action_figures', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'edu_board_games',": "id: 'edu_board_games', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'outdoor_active_play',": "id: 'outdoor_active_play', unitType: 'count', allowedUnits: ['pc', 'set', 'pair'],",
    "id: 'gifts_men_women',": "id: 'gifts_men_women', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'home_decor_showpieces',": "id: 'home_decor_showpieces', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'party_return_gifts',": "id: 'party_return_gifts', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",

    # Bags & Luggage
    "id: 'travel_luggage',": "id: 'travel_luggage', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'daily_backpacks',": "id: 'daily_backpacks', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'ladies_purses',": "id: 'ladies_purses', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'mens_accessories_bags',": "id: 'mens_accessories_bags', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'utility_bags_misc',": "id: 'utility_bags_misc', unitType: 'count', allowedUnits: ['pc', 'pkt'],",

    # Footwear
    "id: 'mens_footwear',": "id: 'mens_footwear', unitType: 'size', allowedUnits: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11', 'UK 12'],",
    "id: 'womens_footwear',": "id: 'womens_footwear', unitType: 'size', allowedUnits: ['UK 3', 'UK 4', 'UK 5', 'UK 6', 'UK 7', 'UK 8'],",
    "id: 'kids_footwear',": "id: 'kids_footwear', unitType: 'size', allowedUnits: ['UK 1', 'UK 2', 'UK 3', 'UK 4', 'UK 5', 'UK 6', 'UK 7', 'UK 8', 'UK 9', 'CH 11', 'CH 12', 'CH 13'],",
    "id: 'shoe_care_acc',": "id: 'shoe_care_acc', unitType: 'count', allowedUnits: ['pc', 'pair', 'pkt'],",

    # Clothing
    "id: 'mens_clothing',": "id: 'mens_clothing', unitType: 'size', allowedUnits: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '36', '38', '40', '42', '44'],",
    "id: 'mens_bottoms',": "id: 'mens_bottoms', unitType: 'size', allowedUnits: ['28', '30', '32', '34', '36', '38', '40', '42'],",
    "id: 'womens_ethnic',": "id: 'womens_ethnic', unitType: 'size', allowedUnits: ['S', 'M', 'L', 'XL', 'XXL', 'FREE SIZE'],",
    "id: 'womens_western_night',": "id: 'womens_western_night', unitType: 'size', allowedUnits: ['S', 'M', 'L', 'XL', 'XXL'],",
    "id: 'kids_wear',": "id: 'kids_wear', unitType: 'size', allowedUnits: ['0-1Y', '1-2Y', '2-3Y', '3-4Y', '5-6Y', '7-8Y', '9-10Y', '11-12Y', '13-14Y'],",
    "id: 'innerwear_lingerie',": "id: 'innerwear_lingerie', unitType: 'size', allowedUnits: ['S', 'M', 'L', 'XL', 'XXL', '75', '80', '85', '90', '95', '100'],",

    # Furnishing
    "id: 'bed_linen',": "id: 'bed_linen', unitType: 'size', allowedUnits: ['Single', 'Double', 'King', 'Queen'],",
    "id: 'blankets_quilts',": "id: 'blankets_quilts', unitType: 'size', allowedUnits: ['Single', 'Double'],",
    "id: 'curtains_blinds',": "id: 'curtains_blinds', unitType: 'size', allowedUnits: ['5ft', '7ft', '9ft'],",
    "id: 'bath_linen',": "id: 'bath_linen', unitType: 'size', allowedUnits: ['Small', 'Medium', 'Large'],",
    "id: 'carpets_mats_home',": "id: 'carpets_mats_home', unitType: 'size', allowedUnits: ['Small', 'Medium', 'Large', 'XL'],",
    "id: 'upholstery_covers_nets',": "id: 'upholstery_covers_nets', unitType: 'size', allowedUnits: ['Single', 'Double', 'Set'],",

    # Lifestyle
    "id: 'imitation_jewellery',": "id: 'imitation_jewellery', unitType: 'count', allowedUnits: ['pc', 'pair', 'set'],",
    "id: 'hair_accessories',": "id: 'hair_accessories', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",
    "id: 'cosmetics_grooming',": "id: 'cosmetics_grooming', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle', 'g', 'ml'],",
    "id: 'sewing_tailoring_home',": "id: 'sewing_tailoring_home', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set', 'roll', 'm'],",
    "id: 'rainwear_seasonal',": "id: 'rainwear_seasonal', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'baby_care_essentials',": "id: 'baby_care_essentials', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle'],",

    # Medical
    "id: 'pain_fever_relief',": "id: 'pain_fever_relief', unitType: 'count', allowedUnits: ['pc', 'strip', 'pkt', 'bottle'],",
    "id: 'cough_cold_allergy',": "id: 'cough_cold_allergy', unitType: 'count', allowedUnits: ['pc', 'strip', 'pkt', 'bottle'],",
    "id: 'digestion_gastric',": "id: 'digestion_gastric', unitType: 'count', allowedUnits: ['pc', 'strip', 'pkt', 'bottle'],",
    "id: 'first_aid_antiseptic',": "id: 'first_aid_antiseptic', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle'],",
    "id: 'skin_personal_pharma',": "id: 'skin_personal_pharma', unitType: 'count', allowedUnits: ['pc', 'strip', 'pkt', 'bottle', 'g', 'ml'],",
    "id: 'baby_pharma_care',": "id: 'baby_pharma_care', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle'],",
    "id: 'immunity_wellness',": "id: 'immunity_wellness', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle', 'kg', 'g'],",
    "id: 'herbal_oils_balms',": "id: 'herbal_oils_balms', unitType: 'count', allowedUnits: ['pc', 'bottle', 'ml'],",
    "id: 'proprietary_ayurvedic',": "id: 'proprietary_ayurvedic', unitType: 'count', allowedUnits: ['pc', 'strip', 'pkt', 'bottle'],",
    "id: 'home_health_monitoring',": "id: 'home_health_monitoring', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'support_rehabilitation',": "id: 'support_rehabilitation', unitType: 'count', allowedUnits: ['pc', 'pair', 'pkt'],",
    "id: 'patient_care_hygiene',": "id: 'patient_care_hygiene', unitType: 'count', allowedUnits: ['pc', 'pkt', 'pair'],",
    "id: 'nutritional_supplements',": "id: 'nutritional_supplements', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle', 'kg', 'g'],",
    "id: 'sexual_wellness',": "id: 'sexual_wellness', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'eye_lens_care',": "id: 'eye_lens_care', unitType: 'count', allowedUnits: ['pc', 'bottle'],",
    "id: 'mother_maternity_care',": "id: 'mother_maternity_care', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'mosquito_insect_repellents',": "id: 'mosquito_insect_repellents', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle'],",
    "id: 'misc_hospital_supplies',": "id: 'misc_hospital_supplies', unitType: 'count', allowedUnits: ['pc', 'pkt', 'set'],",

    # Home Business & Festive
    "id: 'daily_meal_tiffins',": "id: 'daily_meal_tiffins', unitType: 'count', allowedUnits: ['tiffin', 'meal', 'set'],",
    "id: 'dry_snacks_farsan',": "id: 'dry_snacks_farsan', unitType: 'weight_vol', allowedUnits: ['kg', 'g', 'pkt'],",
    "id: 'homemade_sweets',": "id: 'homemade_sweets', unitType: 'weight_vol', allowedUnits: ['kg', 'g', 'pkt', 'pc'],",
    "id: 'home_bakery',": "id: 'home_bakery', unitType: 'count', allowedUnits: ['pc', 'kg', 'g'],",
    "id: 'pickles_masalas',": "id: 'pickles_masalas', unitType: 'weight_vol', allowedUnits: ['kg', 'g', 'pkt', 'bottle'],",
    "id: 'home_decor_trad_art',": "id: 'home_decor_trad_art', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'handmade_jewelry_acc',": "id: 'handmade_jewelry_acc', unitType: 'count', allowedUnits: ['pc', 'pair', 'set'],",
    "id: 'custom_gifts_stationery',": "id: 'custom_gifts_stationery', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'textile_needlework',": "id: 'textile_needlework', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'uttarayan_sankranti',": "id: 'uttarayan_sankranti', unitType: 'count', allowedUnits: ['pc', 'firki', 'dz', 'pkt'],",
    "id: 'holi_colors',": "id: 'holi_colors', unitType: 'weight_vol', allowedUnits: ['kg', 'g', 'pkt', 'pc'],",
    "id: 'navratri_garba',": "id: 'navratri_garba', unitType: 'count', allowedUnits: ['pc', 'set', 'pair'],",
    "id: 'raksha_bandhan',": "id: 'raksha_bandhan', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'diwali_decor',": "id: 'diwali_decor', unitType: 'count', allowedUnits: ['pc', 'set', 'pkt'],",
    "id: 'ganesh_chaturthi',": "id: 'ganesh_chaturthi', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'christmas_decor',": "id: 'christmas_decor', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'sparklers_low_noise',": "id: 'sparklers_low_noise', unitType: 'count', allowedUnits: ['pkt', 'box'],",
    "id: 'sound_crackers',": "id: 'sound_crackers', unitType: 'count', allowedUnits: ['pkt', 'box'],",
    "id: 'sky_fireworks',": "id: 'sky_fireworks', unitType: 'count', allowedUnits: ['pc', 'box'],",
    "id: 'kids_crackers',": "id: 'kids_crackers', unitType: 'count', allowedUnits: ['pkt', 'box'],",
    "id: 'winter_wear_seasonal',": "id: 'winter_wear_seasonal', unitType: 'size', allowedUnits: ['S', 'M', 'L', 'XL', 'XXL', 'Kids'],",
    "id: 'rain_gear_seasonal',": "id: 'rain_gear_seasonal', unitType: 'count', allowedUnits: ['pc'],",
    "id: 'dog_food_treats',": "id: 'dog_food_treats', unitType: 'weight_vol', allowedUnits: ['kg', 'g', 'pkt'],",
    "id: 'cat_food_treats',": "id: 'cat_food_treats', unitType: 'weight_vol', allowedUnits: ['kg', 'g', 'pkt'],",
    "id: 'pet_accessories',": "id: 'pet_accessories', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'grooming_hygiene_pet',": "id: 'grooming_hygiene_pet', unitType: 'count', allowedUnits: ['pc', 'pkt', 'bottle'],",
    "id: 'fish_aquarium_supplies',": "id: 'fish_aquarium_supplies', unitType: 'count', allowedUnits: ['pc', 'pkt'],",
    "id: 'live_plants',": "id: 'live_plants', unitType: 'count', allowedUnits: ['pc', 'pot'],",
    "id: 'pots_planters',": "id: 'pots_planters', unitType: 'count', allowedUnits: ['pc', 'set'],",
    "id: 'soil_fertilizers',": "id: 'soil_fertilizers', unitType: 'weight_vol', allowedUnits: ['kg', 'pkt', 'bag'],",
    "id: 'garden_tools_acc',": "id: 'garden_tools_acc', unitType: 'count', allowedUnits: ['pc', 'set'],",
}

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

for target, replacement in replacements.items():
    content = content.replace(target, replacement)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Final Batch completed.")
